// ─────────────────────────────────────────────────────────────────────────────
// Export layer (PRD §6 Portability, AC-11, AC-12).
//
// One-click PDF (structured, with a table of contents, a drawn radar, sector
// breakdowns, the full roadmap, and the AI-disclosure), plus CSV and JSON.
// ─────────────────────────────────────────────────────────────────────────────

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { countInterventions } from './roadmap.js';

const INK = [14, 27, 42];
const SIGNAL = [14, 165, 164];
const MUTED = [100, 117, 133];
const HAIR = [220, 227, 233];
const TIER_HEX = { Emerging: [224, 122, 69], Developing: [224, 179, 65], Advanced: [63, 166, 107], Leading: [31, 138, 112] };

const DISCLOSURE =
  'This report contains AI-assisted and rules-based recommendations generated by the Community ' +
  'AI Readiness Blueprint. It is decision-support, not professional consulting, legal, or ' +
  'financial advice. Validate findings against local data before acting.';

export function exportPDF(results, roadmap, narrative) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  const community = results.context?.communityName || 'Your Community';
  const date = new Date(results.generatedAt).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
  const tierHex = TIER_HEX[results.overallTier.name] || SIGNAL;

  // ── Cover ──────────────────────────────────────────────────────────────
  doc.setFillColor(...INK).rect(0, 0, W, 220, 'F');
  doc.setTextColor(...SIGNAL).setFont('helvetica', 'bold').setFontSize(10);
  doc.text('COMMUNITY AI READINESS BLUEPRINT', M, 70, { charSpace: 2 });
  doc.setTextColor(255, 255, 255).setFontSize(30);
  doc.text('AI Readiness Scorecard', M, 108);
  doc.setFont('helvetica', 'normal').setFontSize(13).setTextColor(200, 214, 224);
  doc.text(community, M, 134);
  doc.setFontSize(10).setTextColor(150, 170, 186);
  doc.text(date, M, 152);

  // Index dial on cover
  const cx = W - M - 60;
  const cy = 120;
  drawIndexBadge(doc, cx, cy, results.overall, results.overallTier.name, tierHex);

  let y = 260;
  doc.setTextColor(...INK).setFont('helvetica', 'bold').setFontSize(11);
  doc.text(`Overall Readiness Index: ${results.overall}/100  ·  ${results.overallTier.name}  ·  ${results.overallPctLabel} percentile`, M, y);
  y += 24;

  // ── Table of contents ──────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold').setFontSize(13).setTextColor(...INK);
  doc.text('Contents', M, y);
  y += 8;
  doc.setDrawColor(...HAIR).line(M, y, W - M, y);
  y += 18;
  const toc = [
    '1.  Executive Summary',
    '2.  Readiness Scorecard',
    '3.  Sector Breakdown',
    '4.  Critical Gaps & Quick Wins',
    '5.  Equity & Risk Flags',
    '6.  Strategic Roadmap',
    '7.  Methodology & Disclosure',
  ];
  doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(...MUTED);
  toc.forEach((t) => {
    doc.text(t, M, y);
    y += 18;
  });

  // ── 1. Executive Summary ───────────────────────────────────────────────
  doc.addPage();
  y = section(doc, '1.  Executive Summary', M);
  doc.setFont('helvetica', 'normal').setFontSize(10.5).setTextColor(60, 72, 84);
  const sumLines = doc.splitTextToSize(narrative?.executiveSummary || '', W - M * 2);
  doc.text(sumLines, M, y);
  y += sumLines.length * 15 + 10;
  doc.setFontSize(8).setTextColor(...MUTED);
  doc.text(`Source: ${narrative?.source === 'ai' ? 'AI-assisted (Claude) + deterministic engine' : 'Deterministic engine'}  ·  Confidence: ${narrative?.confidence || 'Deterministic'}`, M, y);

  // ── 2. Scorecard ───────────────────────────────────────────────────────
  y = section(doc, '2.  Readiness Scorecard', M, y + 26);
  drawRadar(doc, W / 2, y + 120, 95, results.sectors);
  y += 250;
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [['Sector', 'Weight', 'Score', 'Tier', 'vs Peer']],
    body: results.benchmarks.map((b) => {
      const sec = results.sectors.find((s) => s.id === b.id);
      return [b.name, `${Math.round(sec.weight * 100)}%`, `${b.score}/100`, sec.tier.name, `${b.delta >= 0 ? '+' : ''}${b.delta}`];
    }),
    styles: { font: 'helvetica', fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: INK, textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 249] },
  });

  // ── 3. Sector Breakdown ────────────────────────────────────────────────
  doc.addPage();
  y = section(doc, '3.  Sector Breakdown', M);
  results.sectors.forEach((s) => {
    if (y > 720) { doc.addPage(); y = M + 10; }
    doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(...INK);
    doc.text(`${s.name} — ${s.score}/100 (${s.tier.name})`, M, y);
    y += 14;
    doc.setFont('helvetica', 'normal').setFontSize(9.5).setTextColor(...MUTED);
    const str = 'Strengths: ' + (s.strengths.map((x) => x.indicator).join('; ') || '—');
    const gap = 'Gaps: ' + (s.gaps.map((x) => x.indicator).join('; ') || '—');
    const sl = doc.splitTextToSize(str, W - M * 2);
    const gl = doc.splitTextToSize(gap, W - M * 2);
    doc.text(sl, M, y); y += sl.length * 12;
    doc.text(gl, M, y); y += gl.length * 12 + 12;
  });

  // ── 4. Gaps & Quick Wins ───────────────────────────────────────────────
  if (y > 600) { doc.addPage(); y = M + 10; }
  y = section(doc, '4.  Critical Gaps & Quick Wins', M, y);
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [['Critical Gap', 'Sector', 'Score']],
    body: results.criticalGaps.map((g) => [g.indicator, g.sectorName, `${g.score}/100`]),
    styles: { font: 'helvetica', fontSize: 9.5, cellPadding: 5 },
    headStyles: { fillColor: [217, 83, 79], textColor: 255 },
  });
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 12,
    margin: { left: M, right: M },
    head: [['Quick Win', 'Sector', 'Score']],
    body: results.quickWins.map((q) => [q.indicator, q.sectorName, `${q.score}/100`]),
    styles: { font: 'helvetica', fontSize: 9.5, cellPadding: 5 },
    headStyles: { fillColor: SIGNAL, textColor: 255 },
  });

  // ── 5. Equity & Risk ───────────────────────────────────────────────────
  y = section(doc, '5.  Equity & Risk Flags', M, doc.lastAutoTable.finalY + 28);
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(60, 72, 84);
  const flags = [
    ...results.equityFlags.map((e) => `[EQUITY] ${e.message}`),
    ...results.riskFlags.map((f) => `[${f.severity.toUpperCase()} · ${f.type}] ${f.message}`),
  ];
  if (flags.length === 0) {
    doc.text('No equity or structural risk flags were triggered. Maintain vigilance through annual re-assessment.', M, y);
    y += 20;
  } else {
    flags.forEach((f) => {
      if (y > 760) { doc.addPage(); y = M + 10; }
      const lines = doc.splitTextToSize(f, W - M * 2);
      doc.text(lines, M, y);
      y += lines.length * 13 + 8;
    });
  }

  // ── 6. Roadmap ─────────────────────────────────────────────────────────
  doc.addPage();
  y = section(doc, '6.  Strategic Roadmap', M);
  doc.setFont('helvetica', 'normal').setFontSize(9.5).setTextColor(...MUTED);
  doc.text(`${countInterventions(roadmap)} interventions across 4 phases.`, M, y);
  y += 14;
  roadmap.forEach((phase) => {
    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      head: [[`${phase.name}  ·  ${phase.window}`, 'Sector', 'Effort', 'Impact']],
      body: phase.actions.map((a) => [`${a.title}\n${a.detail}`, a.sector, a.effort, a.impact]),
      styles: { font: 'helvetica', fontSize: 9, cellPadding: 5, valign: 'top' },
      headStyles: { fillColor: INK, textColor: 255 },
      columnStyles: { 0: { cellWidth: 300 }, 1: { cellWidth: 80 } },
      didDrawPage: () => {},
    });
    y = doc.lastAutoTable.finalY + 14;
    if (y > 740) { doc.addPage(); y = M + 10; }
  });

  // ── 7. Methodology & Disclosure ────────────────────────────────────────
  doc.addPage();
  y = section(doc, '7.  Methodology & Disclosure', M);
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(60, 72, 84);
  const method = doc.splitTextToSize(
    'Scores are computed from weighted indicator responses across five sectors (Education 25%, ' +
      'Workforce 25%, Healthcare 20%, Government 20%, Infrastructure 10%). Each sector score is the ' +
      'weighted mean of its answered indicators (0–100). The overall index is the weighted composite. ' +
      'Tiers: Emerging (<40), Developing (40–59), Advanced (60–79), Leading (80+). Benchmark ' +
      'percentiles compare against reference distributions for communities of similar type and size.',
    W - M * 2
  );
  doc.text(method, M, y);
  y += method.length * 14 + 14;
  doc.setDrawColor(...HAIR).setFillColor(245, 247, 249).roundedRect(M, y, W - M * 2, 64, 4, 4, 'FD');
  doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(...INK);
  doc.text('AI DISCLOSURE', M + 12, y + 18);
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(80, 92, 104);
  doc.text(doc.splitTextToSize(DISCLOSURE, W - M * 2 - 24), M + 12, y + 32);

  // Footers
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(...MUTED);
    doc.text(`CARB · ${community}`, M, doc.internal.pageSize.getHeight() - 24);
    doc.text(`${i} / ${pages}`, W - M, doc.internal.pageSize.getHeight() - 24, { align: 'right' });
  }

  doc.save(`CARB_Scorecard_${slug(community)}.pdf`);
}

// ── Drawing helpers ─────────────────────────────────────────────────────────
function section(doc, title, x, y) {
  const yy = y || 64;
  doc.setFont('helvetica', 'bold').setFontSize(15).setTextColor(...INK);
  doc.text(title, x, yy);
  doc.setDrawColor(...SIGNAL).setLineWidth(2).line(x, yy + 6, x + 36, yy + 6);
  doc.setLineWidth(0.5);
  return yy + 26;
}

function drawIndexBadge(doc, cx, cy, score, tier, hex) {
  doc.setDrawColor(60, 80, 100).setLineWidth(6).circle(cx, cy, 46, 'S');
  doc.setDrawColor(...hex).setLineWidth(6);
  // approximate arc with short segments
  const frac = score / 100;
  const steps = Math.max(1, Math.round(frac * 60));
  for (let i = 0; i < steps; i++) {
    const a0 = -Math.PI / 2 + (i / 60) * 2 * Math.PI;
    const a1 = -Math.PI / 2 + ((i + 1) / 60) * 2 * Math.PI;
    doc.line(cx + 46 * Math.cos(a0), cy + 46 * Math.sin(a0), cx + 46 * Math.cos(a1), cy + 46 * Math.sin(a1));
  }
  doc.setLineWidth(0.5);
  doc.setTextColor(255, 255, 255).setFont('helvetica', 'bold').setFontSize(22);
  doc.text(String(score), cx, cy + 4, { align: 'center' });
  doc.setFontSize(8).setTextColor(...hex);
  doc.text(tier.toUpperCase(), cx, cy + 18, { align: 'center' });
}

function drawRadar(doc, cx, cy, R, sectors) {
  const n = sectors.length;
  const ang = (i) => -Math.PI / 2 + (i / n) * 2 * Math.PI;
  // rings
  doc.setDrawColor(...HAIR).setLineWidth(0.5);
  [0.25, 0.5, 0.75, 1].forEach((r) => {
    const pts = [];
    for (let i = 0; i < n; i++) pts.push([cx + R * r * Math.cos(ang(i)), cy + R * r * Math.sin(ang(i))]);
    poly(doc, pts);
  });
  // spokes + labels
  doc.setTextColor(...MUTED).setFont('helvetica', 'normal').setFontSize(8);
  for (let i = 0; i < n; i++) {
    const x = cx + R * Math.cos(ang(i));
    const yy = cy + R * Math.sin(ang(i));
    doc.setDrawColor(...HAIR).line(cx, cy, x, yy);
    const lx = cx + (R + 16) * Math.cos(ang(i));
    const ly = cy + (R + 16) * Math.sin(ang(i));
    doc.text(sectors[i].name, lx, ly, { align: 'center' });
  }
  // data polygon
  const dpts = sectors.map((s, i) => {
    const r = (s.score / 100) * R;
    return [cx + r * Math.cos(ang(i)), cy + r * Math.sin(ang(i))];
  });
  doc.setDrawColor(...SIGNAL).setLineWidth(1.5);
  doc.setFillColor(14, 165, 164);
  doc.setGState(new doc.GState({ opacity: 0.18 }));
  poly(doc, dpts, 'F');
  doc.setGState(new doc.GState({ opacity: 1 }));
  poly(doc, dpts, 'S');
  doc.setLineWidth(0.5);
}

function poly(doc, pts, style = 'S') {
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i];
    const b = pts[(i + 1) % pts.length];
    doc.line(a[0], a[1], b[0], b[1]);
  }
  if (style === 'F') {
    const lines = pts.map((p, i) => (i === 0 ? null : [p[0] - pts[i - 1][0], p[1] - pts[i - 1][1]])).slice(1);
    doc.lines(lines, pts[0][0], pts[0][1], [1, 1], 'F', true);
  }
}

// ── CSV / JSON ──────────────────────────────────────────────────────────────
export function exportCSV(results) {
  const rows = [['Section', 'Item', 'Value']];
  rows.push(['Overall', 'Readiness Index', results.overall]);
  rows.push(['Overall', 'Tier', results.overallTier.name]);
  rows.push(['Overall', 'Percentile', results.overallPctLabel]);
  results.sectors.forEach((s) => {
    rows.push(['Sector Score', s.name, s.score]);
  });
  results.benchmarks.forEach((b) => rows.push(['Benchmark vs Peer', b.name, b.delta]));
  results.criticalGaps.forEach((g, i) => rows.push([`Critical Gap ${i + 1}`, `${g.sectorName} · ${g.indicator}`, g.score]));
  results.quickWins.forEach((q, i) => rows.push([`Quick Win ${i + 1}`, `${q.sectorName} · ${q.indicator}`, q.score]));
  const csv = rows.map((r) => r.map(csvCell).join(',')).join('\n');
  download(csv, `CARB_Scorecard_${slug(results.context?.communityName)}.csv`, 'text/csv');
}

export function exportJSON(results, roadmap, narrative) {
  const payload = { meta: { product: 'CARB', version: '1.0.0' }, results, roadmap, narrative };
  download(JSON.stringify(payload, null, 2), `CARB_Scorecard_${slug(results.context?.communityName)}.json`, 'application/json');
}

function csvCell(v) {
  const s = String(v ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function download(content, filename, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
function slug(s) {
  return (s || 'community').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}
